name: marbleri
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - dask
  - pandas
  - scikit-learn
  - pyyaml
  - pytest
  - distributed
  - pip
  - pyproj
  - jupyter
  - jupyterlab
  - jupyter_server
  - numba
  - sphinx
  - pvlib-python
  - pip:
      - tensorflow==2.5.0
      - keras==2.6.0
      - tensorflow-probability==0.13.0
      - .
