best_track_path: "/Users/dgagne/data/hfip/besttrack_predictors/"
best_track_variables: ["TIME", "LON", "LAT","VMAX", "RMW", "MIN_SLP", "SHR_MAG", "SHR_HDG", "STM_SPD",
                       "STM_HDG", "SST", "TPW", "LAND", "vmax_bt_newer"]
hwrf_variables: ["TMP_P0_L100_GLL0", "TMP_P0_L103_GLL0", "RH_P0_L100_GLL0", "RH_P0_L103_GLL0",
                 "UGRD_P0_L100_GLL0", "UGRD_P0_L103_GLL0", "VGRD_P0_L100_GLL0", "VGRD_P0_L103_GLL0",
                 "PWAT_P0_L200_GLL0", "CAPE_P0_L1_GLL0"]
hwrf_levels: [20000, 50000, 70000, 85000]
hwrf_path: "/Users/dgagne/data/hfip/reforecast/"
out_path: "/Users/dgagne/data/hfip/processed_data/"
process_hwrf: 0
normalize: "local"
n_workers: 32
