hwrf_norm_data_path: "/Users/dgagne/data/hfip/processed_data/hwrf/"
best_track_data_path: "/Users/dgagne/data/hfip/processed_data/best_track_all.csv"
model_out_path: "/Users/dgagne/data/hfip/hfip_models/"
hwrf_variables: ["TMP_P0_L100_GLL0", "TMP_P0_L103_GLL0", "RH_P0_L100_GLL0", "RH_P0_L103_GLL0",
                 "UGRD_P0_L100_GLL0", "UGRD_P0_L103_GLL0", "VGRD_P0_L100_GLL0", "VGRD_P0_L103_GLL0",
                 "PWAT_P0_L200_GLL0", "CAPE_P0_L1_GLL0"]
best_track_inputs: ["TIME", "LAT", "VMAX", "RMW", "MIN_SLP", "SHR_MAG", "SHR_HDG", "STM_SPD",
                         "STM_HDG", "SST", "TPW", "LAND", ]
best_track_output: "vmax_bt_newer"
random_seed: 242907
validation_proportion: 0.2
batch_size: 128
models:
  conv_small:
    model_type: "StandardConvNet"
    config:
      min_filters: 16
      pooling_width: 4
      scalar_hidden_layers: 2
      scalar_hidden_neurons: 100
      output_type: "gaussian"
      pooling: "max"
      data_format: "channels_first"
      optimizer: "sgd"
      batch_size: 512
      epochs: 30
      verbose: 1
      distributed: 1